<?php

/**
 * @file
 *
 * Mautic form popup module.
 */

/**
 * Implements hook_menu().
 */
function mautic_form_popup_menu() {
  $items = array();

  $items['modal_forms/%ctools_js/mautic/%node'] = array(
    'title' => 'Mautic Form',
    'page callback' => 'mautic_form_popup_view',
    'page arguments' => array(1, 3),
    'access callback' => TRUE,
    'file' => 'mautic_form_popup.pages.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter for bounce_convert_campaign_node_form().
 */
function mautic_form_popup_form_bounce_convert_campaign_node_form_alter(&$form, &$form_state) {
  $form['field_bcc_webform'][LANGUAGE_NONE]['#required'] = FALSE;

  $form['field_bcc_webform']['#states']['visible'][':input[name="field_mautic_form[und]"]'] = array('checked' => FALSE);
  $form['field_mautic_form_title']['#states']['visible'][':input[name="field_mautic_form[und]"]'] = array('checked' => TRUE);
  $form['field_mautic_form_html']['#states']['visible'][':input[name="field_mautic_form[und]"]'] = array('checked' => TRUE);

  $form['visibility_title']['#weight'] = 10;
}

/**
 * Implements hook_node_validate().
 */
function mautic_form_popup_node_validate($node, $form, &$form_state) {
  if ($node->type != 'bounce_convert_campaign') {
    return;
  }

  if ($form_state['values']['field_mautic_form'][LANGUAGE_NONE][0]['value'] && empty($form_state['values']['field_mautic_form_html'][LANGUAGE_NONE][0]['value'])) {
    form_set_error('field_mautic_html', t('Form HTML is required.'));
  }
  elseif (empty($form_state['values']['field_mautic_form'][LANGUAGE_NONE][0]['value']) && empty($form_state['values']['field_bcc_webform'][LANGUAGE_NONE][0]['value'])) {
    form_set_error('field_bcc_webform', t('Webform is required.'));
  }
}

/**
 * Implements hook_init().
 */
function mautic_form_popup_init() {
  drupal_add_js(drupal_get_path('module', 'mautic_form_popup') . '/js/mautic_form.js', array('scope' => 'footer'));
  drupal_add_js(drupal_get_path('module', 'mautic_form_popup') . '/js/mautic_form_popup.js', array('scope' => 'footer'));
}

/**
 * Implements hook_page_alter().
 */
function mautic_form_popup_page_alter(&$page) {
  global $user;

  // Fetch only campaigns that user role has permission for that.
  module_load_include('inc', 'bounce_convert', 'bounce_convert.admin');
  $data = bounce_convert_check_campaigns($user->roles);

  if (!$data) {
    return;
  }

  $campaign_id = $data['campaign_node_id'];
  $campaign = node_load($campaign_id);

  $field_mautic_form = field_get_items('node', $campaign, 'field_mautic_form');
  $field_mautic_form = $field_mautic_form[0]['value'];

  if ($field_mautic_form) {
    $bounce_convert_js_param['mautic_form'] = TRUE;
    drupal_add_js(array('bounce_convert' => $bounce_convert_js_param), 'setting');

    global $base_url;
    $extracontent = '<a class="bounce-convert-modal-link ctools-use-modal ctools-modal-bounce-convert-style ctools-modal-modal-popup-medium" style="display:none;" href="' . $base_url . '/modal_forms/nojs/mautic/' . $campaign_id . '" rel="nofollow">Bounce Convert hidden link</a>';

    $page['content']['bounce_convert_modal']['#markup'] = $extracontent;
  }
}
